# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-titanium
    container_name: selenium-hub
    ports:
      - "4446:4444"
  chrome:
    image: selenium/node-chrome:3.141.59-titanium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  firefox:
    image: selenium/node-firefox:3.141.59-titanium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  chrome-debug:
    image: selenium/node-chrome-debug:3.141.59-titanium
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5900:5900"
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  firefox-debug:
    image: selenium/node-firefox-debug:3.141.59-titanium
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5901:5900"
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444